---
title: "SC"
output: html_document
date: "2024-02-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages
```{r}
#install.packages("ggplot2")
library(ggplot2)
#install.packages("ggimage")
library(ggimage)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("nbastatR")
library(nbastatR)
#install.packages("devtools")
library(devtools)
#devtools::install_github("lbenz730/ncaahoopR")
library(ncaahoopR)
#install.packages("extrafont")
library(extrafont)
#font_import()
#install.packages("cowplot")
library(cowplot)
#install.packages("paletteer")
library(paletteer)
#install.packages("formattable")
library(formattable)
Sys.setenv(VROOM_CONNECTION_SIZE = "10000000")
```

# Creating Court 
```{r}
# Creating court and plotting

circle_points = function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(data_frame(x = center[1] + radius * cos(angles),
                    y = center[2] + radius * sin(angles)))
}

# Court Dimensions & lines
width = 50
height = 94 / 2
key_height = 19
inner_key_width = 12
outer_key_width = 16
backboard_width = 6
backboard_offset = 4
neck_length = 0.5
hoop_radius = 0.75
hoop_center_y = backboard_offset + neck_length + hoop_radius
three_point_radius = 23.75
three_point_side_radius = 22
three_point_side_height = 14

# Court themes
court_themes = list(
  light = list(
    court = 'floralwhite',
    lines = '#999999',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = "#000000"
  ),
  dark = list(
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "#000000"
  ),
  ppt = list(
    court = 'gray20',
    lines = 'white',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray20"
)
)

# Function to create court based on given dimensions
plot_court = function(court_theme = court_themes$light, use_short_three = FALSE) {
  if (use_short_three) {
    three_point_radius = 22
    three_point_side_height = 0
  }
  
  court_points = data_frame(
    x = c(width / 2, width / 2, -width / 2, -width / 2, width / 2),
    y = c(height, 0, 0, height, height),
    desc = "perimeter"
  )
  
  court_points = bind_rows(court_points , data_frame(
    x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
    y = c(0, key_height, key_height, 0),
    desc = "outer_key"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset, backboard_offset),
    desc = "backboard"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(0, 0), y = c(backboard_offset, backboard_offset + neck_length), desc = "neck"
  ))
  
  foul_circle = circle_points(center = c(0, key_height), radius = inner_key_width / 2)
  
  foul_circle_top = filter(foul_circle, y > key_height) %>%
    mutate(desc = "foul_circle_top")
  
  foul_circle_bottom = filter(foul_circle, y < key_height) %>%
    mutate(
      angle = atan((y - key_height) / x) * 180 / pi,
      angle_group = floor((angle - 5.625) / 11.25),
      desc = paste0("foul_circle_bottom_", angle_group)
    ) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x, y, desc)
  
  hoop = circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "hoop")
  
  restricted = circle_points(center = c(0, hoop_center_y), radius = 4) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "restricted")
  
  three_point_circle = circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line = data_frame(
    x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
    y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
    desc = "three_point_line"
  )
  
  court_points = bind_rows(
    court_points,
    foul_circle_top,
    foul_circle_bottom,
    hoop,
    restricted,
    three_point_line
  )
  
  
  court_points <- court_points
  
  # Final plot creation
  ggplot() +
    geom_path(
      data = court_points,
      aes(x = x, y = y, group = desc),
      color = court_theme$lines
    ) +
    coord_fixed(ylim = c(0, 45), xlim = c(-25, 25)) +
    theme_minimal(base_size = 22) +
    theme(
      text = element_text(color = court_theme$text),
      plot.background = element_rect(fill = 'gray20', color = 'gray20'),
      panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      legend.background = element_rect(fill = court_theme$court, color = court_theme$court),
      legend.margin = margin(-1, 0, 0, 0, unit = "lines"),
      legend.position = "bottom",
      legend.key = element_blank(),
      legend.text = element_text(size = rel(1.0))
    )
}
```

# NBA Data
```{r}
# Grab team names to type into teams_shots function

nba_teams() %>% filter(isNonNBATeam == 0)

nba_teams_seasons()

# Grab team shot data
mavs <- teams_shots(teams = "Dallas Mavericks", seasons = 2024, season_types = "Regular Season")

# Filter shot data for player & clean data to fit court dimensions
luka <- mavs %>% filter(namePlayer=="Luka Doncic") %>% 
  mutate(x = as.numeric(as.character(locationX)) / 10, y = as.numeric(as.character(locationY)) / 10 + hoop_center_y)

# Horizontally flip the data
luka$x <- luka$x * -1 

# Filter shots by game date
final_luka <- luka %>% filter(dateGame == 20240126)
```

# NBA Chart
```{r}
p1 <- plot_court(court_themes$ppt, use_short_three = F) +
  geom_point(data = final_luka, aes(x = x, y = y, color = final_luka$isShotMade, fill = final_luka$isShotMade), 
             size =3, shape = 21, stroke = .5) +  
  scale_color_manual(values = c("green4","red3"), aesthetics = "color", breaks=c("TRUE", "FALSE"), labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","gray20"), aesthetics = "fill", breaks=c("TRUE", "FALSE"), labels=c("Made", "Missed")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) +
  scale_y_continuous(limits = c(0, 45)) +
  theme(plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.position = c(.5, .95),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  ggtitle(label = "Luka Doncic vs. Atlanta Hawks",
          subtitle = "73 PTS | 10 REB | 7 AST | 8-13 3PT - 1/26/24") +
  labs(caption = "Zemar Loper")

p1 <- ggdraw(p1) +
  draw_image("https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/dal.png&h=200&w=200", 
             x = 0.67, y = 0.75, height = 0.1, width = 0.1) +
  draw_image("https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3945274.png&w=350&h=254", 
             x = 0.65, y = 0.75, height = 0.1, width = 0.1)

ggdraw(p1) + theme(plot.background = element_rect(fill="gray20", color = NA)) 

ggsave("luka.png", height = 6, width = 6, dpi = 1000)
```







```{r}
palette <- paletteer::paletteer_d("RColorBrewer::Blues", direction = -1)

p1 <- plot_court(court_themes$ppt) + 
  geom_density_2d_filled(luka, mapping = aes(x=x,y=y,fill = ..level..,), 
                         contour_var = "ndensity", breaks = seq(0.1, 1.0, length.out = 10), alpha = .7)  + 
  scale_fill_manual(values = c(palette), aesthetics = c("fill", "color")) +
  scale_x_continuous(limits = c(-27.5, 27.5)) + 
  scale_y_continuous(limits = c(0, 45)) +
  theme(legend.position = "none",
        plot.title = element_text(hjust = .5, size = 22, family = "Comic Sans MS", face = "bold", vjust = -4),
        plot.subtitle = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", vjust = -8),
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 10, family = "Comic Sans MS", face = "bold", colour = "white"),
        plot.caption = element_text(hjust = .5, size = 6, family = "Comic Sans MS", face = "bold", colour = "lightgrey", vjust = 8)) +
  labs(title = "Luka Doncic Shot Heatmap",
          subtitle = "2023-2024 Regular Season",
       caption = "Zemar Loper") 

p1 <- ggdraw(p1) +
  draw_image("https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/dal.png&h=200&w=200", 
             x = 0.67, y = 0.75, height = 0.1, width = 0.1) +
  draw_image("https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3945274.png&w=350&h=254", 
             x = 0.65, y = 0.75, height = 0.1, width = 0.1)


ggdraw(p1) + theme(plot.background = element_rect(fill="gray15", color = NA))


ggsave("luka_Heatmap.png", height = 6, width = 6, dpi = 1000)
```


```{r}
player_stats <- nbastatR::players_careers(players = c("Luka Doncic"), modes = c("PerGame")) %>% 
  # filter for regular season 
  filter(nameTable == "SeasonTotalsRegularSeason") %>%
  # pull dataset that is nested in "dataTable" column
  unnest(dataTable) 

```
```{r}
ggplot() +
  # bar chart function from ggplot
  geom_bar(player_stats, mapping = aes(x = slugSeason, y = pts), 
           stat = "identity", position = position_dodge(), fill = "#00538C", color = "white", width = .6) + 
  # set y-axis limits and start ay-xis at 0
  scale_y_continuous(limits=c(0, 35), expand = c(0,0)) +
  # set different labels for plots
  labs(title = "Luka Doncic - Career PPG",
       subtitle = "Zemar Loper",
       x = "Season",
       y = "Points Per Game\n") +
  # add points per game text values inside the bars for easier understanding
  geom_text(player_stats, mapping = aes(x = slugSeason, y = pts, label = pts), 
            position = position_dodge(width = .9), size = 5, family = "Comic Sans MS", color = "white", vjust = 2, face = "bold") +
  # different theme settings to customize the chart
  theme(
        # labels/text
        plot.title = element_text(hjust = .5, size = 14, family = "Comic Sans MS", face = "bold", color = "white"),
        plot.subtitle = element_text(hjust = .5, size = 8, family = "Comic Sans MS", color = "gray50"),
        text = element_text(family = "Comic Sans MS"),
        legend.position = "none",
        # plot background and lines
        plot.background = element_rect(fill="gray15", color = "gray15"),
        panel.background = element_rect(fill="gray15", color = "gray15"),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line(colour = "gray20"),
        panel.grid.major.x = element_blank(),
        axis.line = element_line(colour = "white"),
        # axis
        axis.title.x = element_text(colour = "white", size = 10),
        axis.title.y = element_text(colour = "white", size = 10),
        axis.text.x = element_text(colour = "white", size = 8),
        axis.text.y = element_text(colour = "white", size = 8),
        plot.margin = margin(.5, .5, .5, .5, "cm"),
        # facet 
        strip.background = element_rect(fill="gray20"),
        strip.text = element_text(hjust = .5, size = 8, family = "Comic Sans MS", face = "bold", color = "white"))


# save the lst plot that was created in the environment (this one)
ggsave("lukappg.png", height = 6, width = 6, dpi = "retina")

```

```{r}

player_shooting <- player_stats %>% 
  # select the columns for season, 2P%, 3P%, and FT%
  select(slugSeason, pctFG2, pctFG3, pctFT) %>%
  # rename these columns for clarity
  rename("2PT%" = "pctFG2", "3PT%" = "pctFG3", "FT%" = "pctFT") %>%
  # pivot table from wide to long (will allow us to wrap/group the bar charts by season)
  pivot_longer(!slugSeason, values_to = "value") %>%
  # shorten the names of each season to reduce up clutter on x-axis labels
  mutate(
    slugSeason = case_when(
      slugSeason == "2018-19" ~ "18-19",
      slugSeason == "2019-20" ~ "19-20",
      slugSeason == "2020-21" ~ "20-21",
      slugSeason == "2021-22" ~ "21-22",
      slugSeason == "2022-23" ~ "22-23",
      slugSeason == "2023-24"~ "23-24"
      )) 

# convert the shooting numbers to percentages with one decimal spot
player_shooting$value <- percent(player_shooting$value, 1)

```


```{r}
bar_chart <- ggplot(player_shooting, aes(x = slugSeason, y = value, group = name, fill = name)) +
  geom_bar(stat = "identity", position = position_dodge(), color = "white", width = .6) + 
  scale_y_continuous(limits=c(0, 1), expand = c(0,0), labels = scales::percent_format()) +
  scale_fill_manual(values = c("#002B5E","#B8C4CA", "#000000")) +
  facet_wrap(~name) +
  labs(title = "Luka Doncic - Career Shooting % Trends",
       subtitle = "Zemar Loper",
       x = "Season",
       y = "Shooting Percentage\n") +
  geom_text(aes(label = scales::percent(value/100)), # Corrected label formatting here
            position = position_dodge(width = .9), size = 2, family = "Comic Sans MS", 
            color = "white", vjust = -0.5, face = "bold") + # Adjusted vjust for better label positioning +
  theme(
        plot.title = element_text(hjust = .5, size = 14, family = "Comic Sans MS", face = "bold", color = "white"),
        plot.subtitle = element_text(hjust = .5, size = 8, family = "Comic Sans MS", color = "gray50"),
        text = element_text(family = "Comic Sans MS"),
        legend.position = "none",
        plot.background = element_rect(fill="gray15", color = "gray15"),
        panel.background = element_rect(fill="gray15", color = "gray15"),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_line(colour = "gray20"),
        panel.grid.major.x = element_blank(),
        axis.line = element_line(colour = "white"),
        axis.title.x = element_text(colour = "white", size = 10),
        axis.title.y = element_text(colour = "white", size = 10, margin = margin(r = 10, unit = "pt")), # Adjusted margin here
        axis.text.x = element_text(colour = "white", size = 8),
        axis.text.y = element_text(colour = "white", size = 8, hjust = 1), # Adjusted hjust here
        plot.margin = margin(.5, .5, .5, .5, "cm"),
        strip.background = element_rect(fill="gray20"),
        strip.text = element_text(hjust = .5, size = 8, family = "Comic Sans MS", face = "bold", color = "white")
       )

# Draw the bar chart with images and save the plot
ggdraw(bar_chart) +
  draw_image("https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/dal.png&h=200&w=200", 
             x = .12, y = .64, height = .15, width = .15) +
  draw_image("https://a.espncdn.com/combiner/i?img=/i/headshots/nba/players/full/3945274.png&w=350&h=254", 
             x = .1, y = .64, height = .15, width = .15) 

# Save the last plot that was created in the environment
ggsave("lukapctshoot.png", height = 5, width = 8, dpi = "retina")

```




